Fix for bat git pager bug
When running git log:
```
[bat warning]: Unknown theme 'Monokai Extended', using default.
thread 'main' panicked at 'something is very wrong if the default theme is missing', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/bat-0.21.0/src/assets.rs:205:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```